spring:
  application:
    name: "Price Checker Srv"
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/pricechecker
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      maximum-pool-size: 10
scheduling:
  cron:
    dailyProductExtract: '0 0 0 * * ?'
  zone: 'Europe/Madrid'

server:
  servlet:
    context-path: /api