spring:
  application:
    name: "Price Checker Srv"
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/price_checker
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

scheduling:
  cron:
    dailyProductExtract: '0 0/5 * * * ?'
  zone: 'Europe/Madrid'